cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('update-cart/', views.cart_update, name='cart_update'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('newsletter/', include('newsletter.urls', namespace='newsletter')),
    path('', include('shop.urls', namespace='shop')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('search/', views.SearchListView.as_view(), name='search_list'),
    path('top-sellers/', views.TopSellersView.as_view(), name='top_sellers'),
    path('recently-viewed/', views.RecentlyViewedView.as_view(), name='recently_viewed'),
    path('top-new/', views.TopNewView.as_view(), name='top_new'),
    path('wishlist/', views.WishListView.as_view(), name='wishlist'),
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
    path('<slug:slug>/', views.ProductListView.as_view(), name='product_list_view'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_view', args=[self.slug])


def upload_image(instance, filename):
    return f'images/{instance.name}/{filename}'

class Product(models.Model):
    category = models.ForeignKey(Category, null=True, related_name='Products', on_delete=models.SET_NULL)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.CharField(max_length=200, db_index=True)
    image = models.ImageField(upload_to=upload_image, blank=True)
    description = RichTextField(null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount_percent = models.IntegerField(null=True, blank=True)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('id',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.slug])

    def average_score(self):
        reviews = self.reviews.all()
        reviews_count = reviews.count()
        ranges = None
        if reviews_count > 0:
            ranges = range(round(sum(item.rating for item in reviews) / reviews_count))
        return {'ranges':ranges, 'reviews_count':reviews_count}

def upload_gallery_image(instance, filename):
    return f'images/{instance.product.name}/gallery/{filename}'

class ProductGallery(models.Model):
    image = models.ImageField(upload_to=upload_gallery_image)
    product = models.ForeignKey('Product', related_name='gallery', on_delete=models.CASCADE, null=True, blank=True)


class Review(models.Model):
    product = models.ForeignKey(Product, related_name='reviews', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    rating = models.PositiveSmallIntegerField(default=1)
    description = models.TextField()

    def __str__(self):
        return str(self.product)


class Slider(models.Model):
    title = models.TextField()
    subtitle = models.CharField(max_length=150)
    image = models.ImageField(upload_to='slider/image/')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Set category for slider', help_text='Leave this field blank if you have selected a url')
    url = models.URLField(blank=True, verbose_name='Set url for slider', help_text='Leave this field blank if you have selected a category')

shop/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        exclude = ['product']

        widgets = {
            'rating': forms.HiddenInput(attrs={'min':1, 'max':5}),
            'description': forms.Textarea(attrs={'id':'', 'cols':30, 'rows':30}),
        }


class ContactForm(forms.Form):
    subject = forms.CharField()
    from_email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

shop/views.py
import redis
from django.http.response import Http404, JsonResponse
from django.core.cache import cache
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.core.mail import BadHeaderError
from django.conf import settings
from django.views.generic import ListView
from cart.forms import CartAddProductForm
from .models import Category, Product, Slider
from .forms import ReviewForm, ContactForm
from .tasks import contact_send_mail
from .recommender import Recommender
from .utils import best_selling_products, top_new_ids, inOrder

r = redis.Redis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB, decode_responses=True)

# Create your views here.
def home(request):
    # if 'products' in cache:
    #     products = cache.get('products')
    # else:
    products = Product.objects.filter(available=True)
    #cache.set('products', products, timeout=settings.TIMEOUT_PRODUCTS)

    # Top Sellers
    top_sellers_ids = best_selling_products(products, 3)
    top_sellers = products.filter(id__in=top_sellers_ids)

    # Recently Viewed
    recenlty_viewed_ids = r.lrange('recently_viewd', 0, -1)
    recenlty_viewed_ids = inOrder(recenlty_viewed_ids, 3)
    recently_viewed = list(products.filter(id__in=recenlty_viewed_ids))
    recently_viewed.sort(key=lambda x: recenlty_viewed_ids.index(x.id))

    # Top new
    top_new = products.filter(id__in=top_new_ids(r, 3))

    if 'sliders' in cache:
        sliders = cache.get('sliders')
    else:
        sliders = Slider.objects.all()[:4]
        cache.set('sliders', sliders, timeout=settings.TIMEOUT_SLIDERS)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/index.html', {
        'products': products[:10], 
        'top_sellers': top_sellers, 
        'recently_viewed': recently_viewed, 
        'top_new': top_new,
        'sliders': sliders,
        'cart_product_form':cart_product_form
        }
    )

def product_detail(request, slug):
    product = Product.objects.select_related('category').prefetch_related('gallery').get(slug=slug)
    review_form = ReviewForm(request.POST or None)
    data = {}
    # Post a comment
    if request.is_ajax():
        if review_form.is_valid():
            form = review_form.save(commit=False)
            form.product = product
            form.save()
            data['id'] = product.id
            data['status'] = 'ok'
        else:
            data['error'] = next(iter(review_form.errors.items()))[1][0]
        return JsonResponse(data)
    # Save the latest hits
    r.hsetnx('product_visit', product.id, 0)
    r.hincrby('product_visit', product.id)
    r.lpush('recently_viewd', product.id)
    # Products recommender engine
    recommender = Recommender()
    recommended_products = recommender.suggest_products_for([product], 2)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/detail.html', {'product':product,'form':review_form ,'recommended_products':recommended_products, 'cart_product_form':cart_product_form})

def contact(request):
    message= None
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            try:
                message = 'Email sent successfully, we will reply soon'
                contact_send_mail.delay(cd['subject'], cd['message'], cd['from_email'])
            except BadHeaderError:
                message = 'Invaild header found.'
    else:
        form = ContactForm()
    return render(request, 'shop/contact.html', {'form':form, 'message':message})

class ProductListMixin(object):
    model = Product
    template_name = 'shop/product_list.html'
    context_object_name = 'products'
    paginate_by = 20
    page_title = None

    def get_context_data(self):
        context = super().get_context_data()
        context['cart_product_form'] = CartAddProductForm()
        context['page_title'] = self.page_title
        return context


class SearchListView(ProductListMixin, ListView):
    
    def get_queryset(self):
        qs = super().get_queryset()
        query = self.request.GET.get('s')
        if query is not None:
            products = qs.filter(Q(name__icontains=query))
        else:
            raise Http404
        return products

    def get_context_data(self):
        context = super().get_context_data()
        context['page_title'] = f'search for {self.request.GET.get("s", "")}'
        return context
        

class ProductListView(ProductListMixin, ListView):
    category_title = None

    def get_queryset(self):
        qs = super().get_queryset()
        slug = self.kwargs['slug']
        category = get_object_or_404(Category, slug=slug)
        self.category_title = category.name
        if 'product_list_view' in cache:
            products = cache.get("product_list_view")
        else:
            products = qs.filter(category=category)
            cache.set('product_list_view', products, timeout=settings.TIMEOUT_PRODUCT_LIST_VIEW)
        return products

    def get_context_data(self):
        context = super().get_context_data()
        context['page_title'] = self.category_title
        return context


class TopSellersView(ProductListMixin, ListView):
    page_title = 'Top Sellers'

    def get_queryset(self):
        qs = super().get_queryset()
        products_ids = best_selling_products(qs=qs)
        return qs.filter(id__in=products_ids)


class RecentlyViewedView(ProductListMixin, ListView):
    page_title = 'Recently Viewed'

    def get_queryset(self):
        recenlty_viewed_ids = r.lrange('recently_viewd', 0, -1)
        products_ids = inOrder(recenlty_viewed_ids, len(recenlty_viewed_ids))
        return super().get_queryset().filter(id__in=products_ids)


class TopNewView(ProductListMixin, ListView):
    page_title = 'Top New'

    def get_queryset(self):
        products_ids = top_new_ids(redis=r)
        return super().get_queryset().filter(id__in=products_ids)


class WishListView(ProductListMixin, ListView):
    page_title = 'WishList'

    def get_queryset(self):
            cookie = self.request.COOKIES.get('wishlist')
            products_ids = [int(item) for item in cookie] if cookie  else []
            return super().get_queryset().filter(id__in=products_ids)

templates/shop/inc/brands.html
{% load static %}
<div class="brands-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="brand-wrapper">
                    <div class="brand-list">
                        <img src="{% static 'img/brand1.png' %}" alt="">
                        <img src="{% static 'img/brand2.png' %}" alt="">
                        <img src="{% static 'img/brand3.png' %}" alt="">
                        <img src="{% static 'img/brand4.png' %}" alt="">
                        <img src="{% static 'img/brand5.png' %}" alt="">
                        <img src="{% static 'img/brand6.png' %}" alt="">
                        <img src="{% static 'img/brand1.png' %}" alt="">
                        <img src="{% static 'img/brand2.png' %}" alt="">                            
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> <!-- End brands area -->

templates/shop/inc/promo.html
<div class="promo-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <div class="single-promo promo1">
                    <i class="fa fa-refresh"></i>
                    <p>30 Days return</p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="single-promo promo2">
                    <i class="fa fa-truck"></i>
                    <p>Free shipping</p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="single-promo promo3">
                    <i class="fa fa-lock"></i>
                    <p>Secure payments</p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="single-promo promo4">
                    <i class="fa fa-gift"></i>
                    <p>New products</p>
                </div>
            </div>
        </div>
    </div>
</div> <!-- End promo area -->

templates/shop/inc/slider.html
{% load static %}
<div class="slider-area">
    <!-- Slider -->
    <div class="block-slider block-slider4">
        <ul class="" id="bxslider-home4">
            
            {% for item in sliders %}   
                <li>
                    {% if item.image %}
                        <img src="{{ item.image.url }}" alt="Slide">
                    {% endif %}
                    <div class="caption-group">
                        <h2 class="caption title">
                            {{ item.title|safe }}
                        </h2>
                        <h4 class="caption subtitle">{{ item.subtitle }}</h4>
                        <a class="caption button-radius" href="
                        {% if item.category.get_absolute_url %}
                            {{ item.category.get_absolute_url }}
                        {% else %}
                            {{ item.url }}
                        {% endif %}
                            "><span class="icon"></span>Shop now</a>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
    <!-- ./Slider -->
</div> <!-- End slider area -->

templates/shop/inc/widget.html
{% load static %}
<div class="product-widget-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="single-product-widget">
                    <h2 class="product-wid-title">Top Sellers</h2>
                    <a href="{% url 'shop:top_sellers' %}" class="wid-view-more">View All</a>
                    
                    {% for product in top_sellers %}   
                        <div class="single-wid-product">
                            {% if product.image %}
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{{ product.image.url }}" alt="{{ product.name }}" class="product-thumb">
                                </a>
                            {% endif %}
                            <h2><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h2>
                            <div class="product-wid-rating">
                                {% with reviews as product.average_score %}
                                    {% if reviews.ranges %}
                                        {% for i in average.ranges %}
                                            <i class="fa fa-star"></i>
                                        {% endfor %}
                                        ({{ reviews.reviews_count }})
                                    {% endif %}
                                {% endwith %}
                            </div>
                            <div class="product-wid-price">
                                <ins>${{ product.price }}</ins> <!-- <del>$425.00</del> -->
                            </div>                            
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-4">
                <div class="single-product-widget">
                    <h2 class="product-wid-title">Recently Viewed</h2>
                    <a href="{% url 'shop:recently_viewed' %}" class="wid-view-more">View All</a>
                    
                    {% for product in recently_viewed %}     
                        <div class="single-wid-product">
                            {% if product.image %}
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{{ product.image.url }}" alt="{{ product.name }}" class="product-thumb">
                                </a>
                            {% endif %}
                            <h2><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h2>
                            <div class="product-wid-rating">
                                {% with reviews as product.average_score %}
                                    {% if reviews.ranges %}
                                        {% for i in average.ranges %}
                                            <i class="fa fa-star"></i>
                                        {% endfor %}
                                        ({{ reviews.reviews_count }})
                                    {% endif %}
                                {% endwith %}
                            </div>
                            <div class="product-wid-price">
                                <ins>{{ product.price }}</ins><!--  <del>$425.00</del> -->
                            </div>                            
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-4">
                <div class="single-product-widget">
                    <h2 class="product-wid-title">Top New</h2>
                    <a href="{% url 'shop:top_new' %}" class="wid-view-more">View All</a>
                    
                    {% for product in top_new %}
                        <div class="single-wid-product">
                            {% if product.image %}
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{{ product.image.url }}" alt="{{ product.name }}" class="product-thumb">
                                </a>
                            {% endif %}
                            <h2><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h2>
                            <div class="product-wid-rating">
                                {% with reviews as product.average_score %}
                                    {% if reviews.ranges %}
                                        {% for i in average.ranges %}
                                            <i class="fa fa-star"></i>
                                        {% endfor %}
                                        ({{ reviews.reviews_count }})
                                    {% endif %}
                                {% endwith %}
                            </div>
                            <div class="product-wid-price">
                                <ins>${{ product.price }}</ins> <!-- <del>$425.00</del> -->
                            </div>                            
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div> <!-- End product widget area -->