cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('update-cart/', views.cart_update, name='cart_update'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('newsletter/', include('newsletter.urls', namespace='newsletter')),
    path('', include('shop.urls', namespace='shop')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('search/', views.SearchListView.as_view(), name='search_list'),
    path('top-sellers/', views.TopSellersView.as_view(), name='top_sellers'),
    path('recently-viewed/', views.RecentlyViewedView.as_view(), name='recently_viewed'),
    path('top-new/', views.TopNewView.as_view(), name='top_new'),
    path('wishlist/', views.WishListView.as_view(), name='wishlist'),
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
    path('<slug:slug>/', views.ProductListView.as_view(), name='product_list_view'),
]

templates/part/related_products.html
<div class="related-products-wrapper">
    <h2 class="related-products-title">Recommended products</h2>
    <div class="related-products-carousel">
        {% for item in recommended_products %}
            <div class="single-product">
                <div class="product-f-image">
                    {% if item.image %}
                        <img src="{{ item.image.url }}" alt="{{ item.name }}">
                    {% endif %}
                    <div class="product-hover">
                        <a href="" class="add-to-cart-link"><i class="fa fa-shopping-cart"></i> Add to cart</a>
                        <a href="{{ item.get_absolute_url }}" class="view-details-link"><i class="fa fa-link"></i> See details</a>
                    </div>
                </div>

                <h2><a href="{{ item.get_absolute_url }}">{{ item.name }}</a></h2>

                <div class="product-carousel-price">
                    <ins>${{ item.price }}</ins> <!-- <del>$100.00</del> -->
                </div> 
            </div>    
        {% endfor %}                  
    </div>
</div>

templates/part/single_sidebar.html
<div class="col-md-4">
    <div class="single-sidebar">
        <h2 class="sidebar-title">Search Products</h2>
        <form method="get" action="{% url 'shop:search_list' %}">
            <input type="text" name="s" placeholder="Search products...">
            <input type="submit" value="Search">
        </form>
    </div>
    
    <div class="single-sidebar">
        <h2 class="sidebar-title">Products</h2>
        {% for item in latest_products %}
            <div class="thubmnail-recent">
                {% if item.image %}
                    <img src="{{ item.image.url }}" class="recent-thumb" alt="{{ item.name }}">
                {% endif %}
                <h2><a href="{{ item.get_absolute_url }}">{{ item.name }}></a></h2>
                <div class="product-sidebar-price">
                    <ins>${{ item.price }}</ins> <!-- <del>$100.00</del> -->
                </div>                             
            </div>
        {% endfor %}
    </div>
    
    <!-- <div class="single-sidebar">
        <h2 class="sidebar-title">Recent Posts</h2>
        <ul>
            <li><a href="">Sony Smart TV - 2015</a></li>
            <li><a href="">Sony Smart TV - 2015</a></li>
            <li><a href="">Sony Smart TV - 2015</a></li>
            <li><a href="">Sony Smart TV - 2015</a></li>
            <li><a href="">Sony Smart TV - 2015</a></li>
        </ul>
    </div> -->
</div>