cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('update-cart/', views.cart_update, name='cart_update'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('newsletter/', include('newsletter.urls', namespace='newsletter')),
    path('', include('shop.urls', namespace='shop')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

newsletter/urls.py
from django.urls import path
from . import views

app_name = 'newsletter'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('confirm/', views.confirm, name='confirm'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('search/', views.SearchListView.as_view(), name='search_list'),
    path('top-sellers/', views.TopSellersView.as_view(), name='top_sellers'),
    path('recently-viewed/', views.RecentlyViewedView.as_view(), name='recently_viewed'),
    path('top-new/', views.TopNewView.as_view(), name='top_new'),
    path('wishlist/', views.WishListView.as_view(), name='wishlist'),
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
    path('<slug:slug>/', views.ProductListView.as_view(), name='product_list_view'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_view', args=[self.slug])


def upload_image(instance, filename):
    return f'images/{instance.name}/{filename}'

class Product(models.Model):
    category = models.ForeignKey(Category, null=True, related_name='Products', on_delete=models.SET_NULL)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.CharField(max_length=200, db_index=True)
    image = models.ImageField(upload_to=upload_image, blank=True)
    description = RichTextField(null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount_percent = models.IntegerField(null=True, blank=True)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('id',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.slug])

    def average_score(self):
        reviews = self.reviews.all()
        reviews_count = reviews.count()
        ranges = None
        if reviews_count > 0:
            ranges = range(round(sum(item.rating for item in reviews) / reviews_count))
        return {'ranges':ranges, 'reviews_count':reviews_count}

def upload_gallery_image(instance, filename):
    return f'images/{instance.product.name}/gallery/{filename}'

class ProductGallery(models.Model):
    image = models.ImageField(upload_to=upload_gallery_image)
    product = models.ForeignKey('Product', related_name='gallery', on_delete=models.CASCADE, null=True, blank=True)


class Review(models.Model):
    product = models.ForeignKey(Product, related_name='reviews', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    rating = models.PositiveSmallIntegerField(default=1)
    description = models.TextField()

    def __str__(self):
        return str(self.product)


class Slider(models.Model):
    title = models.TextField()
    subtitle = models.CharField(max_length=150)
    image = models.ImageField(upload_to='slider/image/')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Set category for slider', help_text='Leave this field blank if you have selected a url')
    url = models.URLField(blank=True, verbose_name='Set url for slider', help_text='Leave this field blank if you have selected a category')

shop/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        exclude = ['product']

        widgets = {
            'rating': forms.HiddenInput(attrs={'min':1, 'max':5}),
            'description': forms.Textarea(attrs={'id':'', 'cols':30, 'rows':30}),
        }


class ContactForm(forms.Form):
    subject = forms.CharField()
    from_email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

shop/views.py
import redis
from django.http.response import Http404, JsonResponse
from django.core.cache import cache
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.core.mail import BadHeaderError
from django.conf import settings
from django.views.generic import ListView
from cart.forms import CartAddProductForm
from .models import Category, Product, Slider
from .forms import ReviewForm, ContactForm
from .tasks import contact_send_mail
from .recommender import Recommender
from .utils import best_selling_products, top_new_ids, inOrder

r = redis.Redis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB, decode_responses=True)

# Create your views here.
def home(request):
    # if 'products' in cache:
    #     products = cache.get('products')
    # else:
    products = Product.objects.filter(available=True)
    #cache.set('products', products, timeout=settings.TIMEOUT_PRODUCTS)

    # Top Sellers
    top_sellers_ids = best_selling_products(products, 3)
    top_sellers = products.filter(id__in=top_sellers_ids)

    # Recently Viewed
    recenlty_viewed_ids = r.lrange('recently_viewd', 0, -1)
    recenlty_viewed_ids = inOrder(recenlty_viewed_ids, 3)
    recently_viewed = list(products.filter(id__in=recenlty_viewed_ids))
    recently_viewed.sort(key=lambda x: recenlty_viewed_ids.index(x.id))

    # Top new
    top_new = products.filter(id__in=top_new_ids(r, 3))

    if 'sliders' in cache:
        sliders = cache.get('sliders')
    else:
        sliders = Slider.objects.all()[:4]
        cache.set('sliders', sliders, timeout=settings.TIMEOUT_SLIDERS)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/index.html', {
        'products': products[:10], 
        'top_sellers': top_sellers, 
        'recently_viewed': recently_viewed, 
        'top_new': top_new,
        'sliders': sliders,
        'cart_product_form':cart_product_form
        }
    )

def product_detail(request, slug):
    product = Product.objects.select_related('category').prefetch_related('gallery').get(slug=slug)
    review_form = ReviewForm(request.POST or None)
    data = {}
    # Post a comment
    if request.is_ajax():
        if review_form.is_valid():
            form = review_form.save(commit=False)
            form.product = product
            form.save()
            data['id'] = product.id
            data['status'] = 'ok'
        else:
            data['error'] = next(iter(review_form.errors.items()))[1][0]
        return JsonResponse(data)
    # Save the latest hits
    r.hsetnx('product_visit', product.id, 0)
    r.hincrby('product_visit', product.id)
    r.lpush('recently_viewd', product.id)
    # Products recommender engine
    recommender = Recommender()
    recommended_products = recommender.suggest_products_for([product], 2)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/detail.html', {'product':product,'form':review_form ,'recommended_products':recommended_products, 'cart_product_form':cart_product_form})

def contact(request):
    message= None
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            try:
                message = 'Email sent successfully, we will reply soon'
                contact_send_mail.delay(cd['subject'], cd['message'], cd['from_email'])
            except BadHeaderError:
                message = 'Invaild header found.'
    else:
        form = ContactForm()
    return render(request, 'shop/contact.html', {'form':form, 'message':message})

class ProductListMixin(object):
    model = Product
    template_name = 'shop/product_list.html'
    context_object_name = 'products'
    paginate_by = 20
    page_title = None

    def get_context_data(self):
        context = super().get_context_data()
        context['cart_product_form'] = CartAddProductForm()
        context['page_title'] = self.page_title
        return context


class SearchListView(ProductListMixin, ListView):
    
    def get_queryset(self):
        qs = super().get_queryset()
        query = self.request.GET.get('s')
        if query is not None:
            products = qs.filter(Q(name__icontains=query))
        else:
            raise Http404
        return products

    def get_context_data(self):
        context = super().get_context_data()
        context['page_title'] = f'search for {self.request.GET.get("s", "")}'
        return context
        

class ProductListView(ProductListMixin, ListView):
    category_title = None

    def get_queryset(self):
        qs = super().get_queryset()
        slug = self.kwargs['slug']
        category = get_object_or_404(Category, slug=slug)
        self.category_title = category.name
        if 'product_list_view' in cache:
            products = cache.get("product_list_view")
        else:
            products = qs.filter(category=category)
            cache.set('product_list_view', products, timeout=settings.TIMEOUT_PRODUCT_LIST_VIEW)
        return products

    def get_context_data(self):
        context = super().get_context_data()
        context['page_title'] = self.category_title
        return context


class TopSellersView(ProductListMixin, ListView):
    page_title = 'Top Sellers'

    def get_queryset(self):
        qs = super().get_queryset()
        products_ids = best_selling_products(qs=qs)
        return qs.filter(id__in=products_ids)


class RecentlyViewedView(ProductListMixin, ListView):
    page_title = 'Recently Viewed'

    def get_queryset(self):
        recenlty_viewed_ids = r.lrange('recently_viewd', 0, -1)
        products_ids = inOrder(recenlty_viewed_ids, len(recenlty_viewed_ids))
        return super().get_queryset().filter(id__in=products_ids)


class TopNewView(ProductListMixin, ListView):
    page_title = 'Top New'

    def get_queryset(self):
        products_ids = top_new_ids(redis=r)
        return super().get_queryset().filter(id__in=products_ids)


class WishListView(ProductListMixin, ListView):
    page_title = 'WishList'

    def get_queryset(self):
            cookie = self.request.COOKIES.get('wishlist')
            products_ids = [int(item) for item in cookie] if cookie  else []
            return super().get_queryset().filter(id__in=products_ids)

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<!--
	ustora by freshdesignweb.com
	Twitter: https://twitter.com/freshdesignweb
	URL: https://www.freshdesignweb.com/ustora/
-->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ustore{% block title %}{% endblock %}</title>
    
    <!-- Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,300,700,600' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>
    
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
   
    <div class="header-area">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="user-menu">
                        <ul>
                            <li><a href="{% url 'dashboard' %}"><i class="fa fa-user"></i> My Account</a></li>
                            <li><a href="{% url 'shop:product_list_view' 'wishlist' %}"><i class="fa fa-heart"></i> Wishlist</a></li>
                            <li><a href="{% url 'cart:cart_detail' %}"><i class="fa fa-user"></i> My Cart</a></li>
                            <li><a href="{% url 'orders:order_create' %}"><i class="fa fa-user"></i> Checkout</a></li>
                            
                            {% if request.user.is_authenticated %}
                                <li><a href="{% url 'password_change' %}"><i class="fa fa-user"></i> Change your password</a></li>
                                <li><a href="{% url 'logout' %}"><i class="fa fa-user"></i> Logout</a></li>
                            {% else %}
                                <li><a href="{% url 'login' %}"><i class="fa fa-user"></i> Login</a></li>
                            {% endif %}                       
                        </ul>
                    </div>
                </div>
                
                <!-- <div class="col-md-4">
                    <div class="header-right">
                        <ul class="list-unstyled list-inline">
                            <li class="dropdown dropdown-small">
                                <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#"><span class="key">currency :</span><span class="value">USD </span><b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">USD</a></li>
                                    <li><a href="#">INR</a></li>
                                    <li><a href="#">GBP</a></li>
                                </ul>
                            </li>

                            <li class="dropdown dropdown-small">
                                <a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" href="#"><span class="key">language :</span><span class="value">English </span><b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">English</a></li>
                                    <li><a href="#">French</a></li>
                                    <li><a href="#">German</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div> -->
            </div>
        </div>
    </div> <!-- End header area -->
    
    <div class="site-branding-area">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="logo">
                        <h1><a href="/"><img src="{% static 'img/logo.png' %}"></a></h1>
                    </div>
                </div>
                
                <div class="col-sm-6">
                    <div class="shopping-item">
                        <a href="{% url 'cart:cart_detail' %}">Cart - <span class="cart-amunt">${{ cart.get_total_price }}</span> <i class="fa fa-shopping-cart"></i> <span class="product-count">{{ cart|length }}</span></a>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End site branding area -->

    <div class="mainmenu-area">
        <div class="container">
            <div class="row">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div> 
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="/">Home</a></li>
                        <li><a href="{% url 'cart:cart_detail' %}">Cart</a></li>
                        <li><a href="{% url 'orders:order_create' %}">Checkout</a></li>
                        <li><a href="{% url 'shop:contact' %}">Contact</a></li>
                    </ul>
                </div>  
            </div>
        </div>
    </div> <!-- End mainmenu area -->

    {% block content %}
    
    {% endblock %}

    {% include 'footer.html' %}
   
    <!-- Latest jQuery form server -->
    <script src="https://code.jquery.com/jquery.min.js"></script>
    
    <!-- Bootstrap JS form CDN -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    
    <!-- jQuery sticky menu -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.sticky.js' %}"></script>
    
    <!-- jQuery easing -->
    <script src="{% static 'js/jquery.easing.1.3.min.js' %}"></script>
    
    <!-- Main Script -->
    <script src="{% static 'js/main.js' %}"></script>
    
    <!-- Slider -->
    <script type="text/javascript" src="{% static 'js/bxslider.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/script.slider.js' %}"></script>
    
    {% block javascript %}
        
    {% endblock %}
        
  </body>
</html>

shop/templates/footer.html
{% load static %}
<div class="footer-top-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-6">
                <div class="footer-about-us">
                    <h2>u<span>Stora</span></h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis sunt id doloribus vero quam laborum quas alias dolores blanditiis iusto consequatur, modi aliquid eveniet eligendi iure eaque ipsam iste, pariatur omnis sint! Suscipit, debitis, quisquam. Laborum commodi veritatis magni at?</p>
                    <div class="footer-social">
                        <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
                        <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                        <a href="#" target="_blank"><i class="fa fa-youtube"></i></a>
                        <a href="#" target="_blank"><i class="fa fa-linkedin"></i></a>
                    </div>
                </div>
            </div>
            
            <div class="col-md-4 col-sm-6">
                <div class="footer-menu">
                    <h2 class="footer-wid-title">Categories</h2>
                    <ul>
                        {% for category in categories %}
                            <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>                        
                </div>
            </div>
            
            <div class="col-md-4 col-sm-6">
                <div class="footer-newsletter">
                    <h2 class="footer-wid-title">Newsletter</h2>
                    <p>Sign up to our newsletter and get exclusive deals you wont find anywhere else straight to your inbox!</p>
                    <div class="newsletter-form">
                        <form action="{% url 'newsletter:new' %}" method="POST">
                            {% csrf_token %}
                            {{ form.email }}
                            <input type="submit" value="Subscribe">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> <!-- End footer top area -->

<div class="footer-bottom-area">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="copyright">
                    <p>&copy; 2021 UStore. All Rights Reserved. <a href="http://www.freshdesignweb.com" target="_blank">freshDesignweb.com</a></p>
                </div>
            </div>
            
            <div class="col-md-4">
                <div class="footer-card-icon">
                    <i class="fa fa-cc-discover"></i>
                    <i class="fa fa-cc-mastercard"></i>
                    <i class="fa fa-cc-paypal"></i>
                    <i class="fa fa-cc-visa"></i>
                </div>
            </div>
        </div>
    </div>
</div> <!-- End footer bottom area -->